---
- name: Uploads | Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Uploads | Restart sync daemon
  ansible.builtin.systemd:
    name: "s3-uploads-sync@{{ fqdn }}"
    state: restarted
    daemon_reload: true
  failed_when: false

- name: Uploads | Restart perm watcher
  ansible.builtin.systemd:
    name: "web-perm-watcher@{{ fqdn }}"
    state: restarted
    daemon_reload: true
  failed_when: false
